kino_site/kino_site/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('accounts/', include('allauth.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('contact/', include("contact.urls")),
    path('', include("movie.urls")),
)

# from django.urls import re_path
# from django.contrib.flatpages import views
#
# # Your other patterns here
# urlpatterns += [
#     re_path(r'^(?P<url>.*/)$', views.flatpage),
# ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kino_site/movie/urls.py
from django.urls import path
# #
from . import views


urlpatterns = [
    path("", views.MoviesView.as_view()),
    path("filter/", views.FilterMoviesView.as_view(), name='filter'),
    path("search/", views.Search.as_view(), name='search'),
    path("add-rating/", views.AddStarRating.as_view(), name='add_rating'),
    path("review/<int:pk>/", views.AddReviewView.as_view(), name="review-movie"),
    path("<slug:slug>/", views.MovieDetailView.as_view(), name="movie-detail"),
    path("actor/<str:slug>/", views.ActorView.as_view(), name="actor_detail"),
]

kino_site/movie/models.py
from django.db import models
from datetime import  date
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    #если поле в name не будет указано, оно заполнится как "Категория"
    name = models.CharField("Категория", max_length=200)
    # если поле в name не будет указано, оно заполнится как "Описание"
    description = models.TextField("Описание")
    #slugfield - поле, содержащее цифры, буквы, подчеркивания и дефисы
    url = models.SlugField(max_length = 160, unique=True)

    def __str__(self):
        return self.name

#Контейнер класса с некоторыми опциями метаданных, прикрепленные к модели.
#Он определяет является ли модель абстрактной, имя связанной базы данных, единственное и мн число имени и тд
    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

class Actor(models.Model):
    name = models.CharField("Имя", max_length=100)
    age = models.PositiveSmallIntegerField("Возраст", default = 0)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="actors/")

    def __str__(self):
        return (self.name)

    def get_absolute_url(self):
        return reverse('actor_detail', kwargs = {"slug": self.name})

    class Meta:
        verbose_name = "Актеры и режиссеры"
        verbose_name_plural = "Актеры и режиссеры"

class Genre(models.Model):
    name = models.CharField("Имя", max_length=100)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160, unique=True)
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанры"

class Movie(models.Model):
    title = models.CharField("Название", max_length=100)
    tagline = models.CharField("Слоган", max_length=100, default ='')
    description = models.TextField("Описание")
    poster = models.ImageField("Постер", upload_to="movies/")
    year = models.PositiveSmallIntegerField("Дата выхода", default= 2021)
    country = models.CharField("Страна", max_length=30)
    directors = models.ManyToManyField(Actor, verbose_name="режиссер", related_name="film_director")
    actors = models.ManyToManyField(Actor, verbose_name="актеры", related_name="film_actors")
    genres = models.ManyToManyField(Genre, verbose_name="Жанры")
    world_premiere = models.DateField("Премьера в мире", default = date.today)
    budget = models.PositiveIntegerField("Бюджет", default=0, help_text="Указывать сумму в долларах")
    fees_in_usa = models.PositiveIntegerField("Сборы в США", default=0, help_text="Указывать сумму в долларах")
    fees_in_world = models.PositiveIntegerField("Сборы в Мире", default=0, help_text="Указывать сумму в долларах")
    url = models.SlugField(max_length=160, unique=True)
    category = models.ForeignKey(Category, verbose_name="Категория", on_delete=models.SET_NULL, null=True)
    draft = models.BooleanField("Черновик", default = False)

    def __str__(self):
        return self.title

    def get_review(self):
        return self.reviews_set.filter(parent__isnull=True)

    def get_absolute_url(self):
        return reverse('movie-detail', kwargs={"slug": self.url})

    class Meta:
        verbose_name = "Фильм"
        verbose_name_plural = "Фильмы"

class MovieShots(models.Model):
    title = models.CharField("Заголовок", max_length=100)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="movie_shots/")
    movie = models.ForeignKey(Movie, verbose_name="Фильм", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Кадр из фильма"
        verbose_name_plural = "Кадры из фильма"

class RatingStar(models.Model):
    value = models.SmallIntegerField("Значение", default = 0)
    
    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name = "Звезда рейтинга"
        verbose_name_plural = "Звезды рейтинга"
        ordering = ["-value"]

class Rating(models.Model):
    ip = models.CharField("Ip адрес", max_length = 15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name="звезда")
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name="фильм")

    def __str__(self):
        return f'{self.star} - {self.movie}'

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"

class Reviews(models.Model):
    email = models.EmailField()
    name = models.CharField("Имя", max_length=100)
    text = models.TextField("Сообщение", max_length=5000)
    parent = models.ForeignKey('self', verbose_name="Родитель", on_delete=models.SET_NULL, blank=True, null=True)
    movie = models.ForeignKey(Movie, verbose_name="Фильм", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.movie}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

kino_site/movie/forms.py
from django import forms
from .models import Reviews, RatingStar, Rating
from snowpenguin.django.recaptcha3.fields import ReCaptchaField

class ReviewForm(forms.ModelForm):
    captcha = ReCaptchaField()
    class Meta:
        model = Reviews
        fields = ("name", "email", "text", "captcha")
        #widgets необходимы для рендеринга формы со стилями, которые описали
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control-border"}),
            "email": forms.EmailInput(attrs={"class": "form-control-border"}),
            "text": forms.Textarea(attrs={"class": "form-control-border"})
        }

class RatingForm(forms.ModelForm):
    #queryset - для вывода выбора всех вариантов для пользователя
    star = forms.ModelChoiceField(queryset = RatingStar.objects.all(), widget = forms.RadioSelect(), empty_label=None)
    class Meta:
        model = Rating
        fields = ("star", )

kino_site/movie/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, View
from .models import Movie, Reviews, Category, Actor, Genre, Rating
from .forms import ReviewForm, RatingForm
from django.shortcuts import redirect
import inspect
from django.db.models import Q
from django.http import JsonResponse
import json
from django.http import HttpResponse
from django.urls import reverse
from django.core.paginator import Paginator

# Create your views here.

class Pages:
    """Страницы"""
    def get_pages(self, context):
        p = Paginator(self.queryset, self.paginate_by)
        middle = []
        left_dot, right_dot = True, True
        if (context["page_obj"].has_previous()):
            middle.append(context["page_obj"].previous_page_number())
        if (p.num_pages > 0):
            middle.append(context["page_obj"].number)
        if (context["page_obj"].has_next()):
            middle.append(context["page_obj"].next_page_number())
        left = [x for x in range(1,3) if x not in middle]
        right = [x for x in range(p.num_pages - 1, p.num_pages + 1) if x not in middle]
        if (len(left) == 0 or (len(left) > 0 and left[-1] == middle[0] - 1)):
            left_dot = False
        if (len(right) == 0 or (len(right) > 0 and right[0] == middle[-1] + 1)):
            right_dot = False
        page_dict = {"left": left, "middle": middle, "right": right, "right_dot": right_dot, "left_dot": left_dot}
        context.update(page_dict)
        return context


class GenreYear:
    """Жанры и года"""
    def get_genres(self):
        return Genre.objects.all()

    def get_years(self):
        return Movie.objects.filter(draft=False).values("year")

class ActorView(GenreYear, DetailView):
    model = Actor
    template_name = "templates/movie/actor.html"
    slug_field = 'name'

class MoviesView(GenreYear, ListView):
    # При http get-запросе вызывается данный метод
    model = Movie
    queryset = Movie.objects.filter(draft = False)
    paginate_by = 1
    template_name = "templates/movie/movie_list.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context = Pages.get_pages(self, context)
        return context

class FilterMoviesView(GenreYear, ListView):
    """Фильтр фильмов"""
    template_name = "templates/movie/movie_list.html"
    paginate_by = 1

    def get_queryset(self):
        #Будем фильтровать фильмы там, где года будут входить в список, который нам будет возвращаться
        queryset = Movie.objects.filter(Q(year__in = self.request.GET.getlist("year")) |
                                        Q(genres__in = self.request.GET.getlist("genre"))).distinct()
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["year"] = ''.join([f"year={x}&" for x in self.request.GET.getlist("year")])
        context["genre"] = ''.join([f"genre={x}&" for x in self.request.GET.getlist("genre")])
        self.queryset = self.get_queryset()
        context = Pages.get_pages(self, context)
        return context


class MovieDetailView(GenreYear, DetailView):
    model = Movie
    slug_field = 'url'
    template_name = "templates/movie/movie_detail.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        #RatingForm() - закладываем значения формы в контекст
        # Для передачи в шаблон данных. Форма должна показываться на странице!
        context["star_form"] = RatingForm()
        context["form"] = ReviewForm()
        return context


class AddReviewView(View):
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        movie = Movie.objects.get(id = pk)
        if form.is_valid():
            form = form.save(commit=False)
            if (request.POST.get("parent", None)):
                form.parent_id = int(request.POST.get("parent"))
            form.movie = movie
            form.save()
        return redirect(movie.get_absolute_url())

class AddStarRating(View):
    def get_client_ip(self, request):
        x_forwarded_for = request.META.get("HTTP_X_FORWARDED_FOR")
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get("REMOTE_ADDR")
        return ip

    def post(self, request):
        form = RatingForm(request.POST)
        if (form.is_valid()):
        #defaults - словарь, который необходим для обновления, movie_id и ip не будут обновляться
        # при дальнейшем изменении ip и movie_id меняться не будут
            Rating.objects.update_or_create(ip = self.get_client_ip(request),
                                            movie_id = int(request.POST.get("movie")),
                                            defaults = {'star_id': int(request.POST.get("star"))})
            movie_obj = Movie.objects.get(id=request.POST.get("movie"))
            return redirect(movie_obj.get_absolute_url())
        else:
            return HttpResponse(status=400)

class Search(ListView):
    model = Movie
    paginate_by = 1
    template_name = "templates/movie/movie_list.html"

    def get_queryset(self):
    #icontains - для фильтрации без учета регистра
        return Movie.objects.filter(title__icontains=self.request.GET.get("q"))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        self.queryset = self.get_queryset()
        context["title"] = f'q={self.request.GET.get("q")}&'
        context = Pages.get_pages(self, context)
        return context

kino_site/templates/movie/actor.html
{% extends 'templates/movie/base.html' %}
{% load static %}
{% block title %} {{ actor.name }} {% endblock title %}
{% block container %}
<div class="container py-md-3">
    {% endblock container %}

    {% block sidebar %}
    <div class="side-bar col-lg-4">
        {% endblock sidebar %}

        {% block movie %}
        <div class="left-ads-display col-lg-8">
            <div class="row">
                <div class="desc1-left col-md-6">
                    <img src="{{ actor.image.url }}" class="img-fluid" alt="">
                </div>
                <div class="desc1-right col-md-6 pl-lg-4">
                    <h3 class="editContent" style="outline: none; cursor: inherit;">
                        {{ movie.title }}
                    </h3>
                    <h5 class="editContent"></h5>
                    <ul>
                        <li>
                            <span><b>Возраст:</b> {{ actor.age }} лет</span></li>
                        <li>
                                    <span><b>Режиссер:</b>
                                        {% for movie in actor.film_director.all %}
                                        {{ movie.title }}
                                        {% endfor %}
                                    </span>
                        </li>
                        <li><span><b>Актеры:</b>
                                    {% for movie in actor.film_actors.all %}
                                        {{ movie.title }}
                                    {% endfor %}
                                </span>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="row sub-para-w3layouts mt-5">
                <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                    О {{ actor.name }}
                </h3>
                <p class="editContent">
                    {{ actor.description|safe }}
                </p>
            </div>
        </div>
{% endblock movie %}

kino_site/templates/movie/base.html
{% extends 'templates/base.html' %}

{% block content %}
<section class="ab-info-main py-md-5 py-4 editContent" style="padding-left: 3rem; padding-right: 3rem;">
    {% block container %}
    <div class="container-fluid py-md-3">
        {% endblock container %}
        <div class="row">
            {% block sidebar %}
            <div class="side-bar col-lg-3">
                {% endblock sidebar %}
                {% include 'templates/include/sidebar.html' %}
            </div>
            {% block movie %}
            {% endblock movie %}
        </div>
    </div>
</section>
{% endblock content %}

kino_site/templates/movie/movie_detail.html
{% extends 'templates/movie/base.html' %}
{% load static i18n %}
{% block container %}
<div class="container py-md-3">
    {% endblock container %}

    {% block sidebar %}
    <div class="side-bar col-lg-4">
        {% endblock sidebar %}

        {% block movie %}
        <div class="left-ads-display col-lg-8">
            <div class="row">
                <div class="desc1-left col-md-6">
                    <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
                </div>
                <div class="desc1-right col-md-6 pl-lg-4">
                    <h3 class="editContent" style="outline: none; cursor: inherit;">
                        {{ movie.title }}
                    </h3>
                    <h5 class="editContent"></h5>
                    <ul>
                        <li style="list-style: none">
                            <span><b>{% blocktrans %} Год {% endblocktrans %}:</b> {{ movie.year }}</span></li>
                        <li style="list-style: none">
                            <span><b>{% blocktrans %} Страна {% endblocktrans %}:</b> {{ movie.country }}</span>
                        </li>
                        <li style="list-style: none">
                            <span><b>{% blocktrans %} Слоган {% endblocktrans %}:</b> {{ movie.tagline }}</span>
                        </li>
                        <li style="list-style: none">
                                    <span><b>{% blocktrans %} Режиссер {% endblocktrans %}:</b>
                                        {% for director in movie.directors.all %}
                                        <a href="{{ director.get_absolute_url }}">{{ director.name }}</a>
                                        {% endfor %}
                                    </span>
                        </li>
                        <li style="list-style: none"><span><b>{% blocktrans %} Актеры {% endblocktrans %}:</b>
                                    {% for actor in movie.actors.all %}
                                        <a href="{{ actor.get_absolute_url }}">{{ actor.name }}</a>
                                        {% endfor %}
                                </span>
                        </li>
                        <li style="list-style: none"><span><b>{% blocktrans %} Жанр {% endblocktrans %}:</b>
                                    {% for genre in movie.genres.all %}
                                        {{ genre.name }}
                                    {% endfor %}
                                    </span>
                        </li>
                        <li style="list-style: none"><span><b>{% blocktrans %} Премьера в мире {% endblocktrans %}: </b> {{ movie.world_premiere }}</span>
                        </li>
                        <li style="list-style: none">
                            <span><b>{% blocktrans %} Бюджет {% endblocktrans %}:</b> ${{ movie.budget }}</span></li>
                        <li style="list-style: none">
                            <span><b>{% blocktrans %}Сборы в США {% endblocktrans %}:</b> ${{ movie.fees_in_usa }}</span></li>
                        <li style="list-style: none"><span><b>{% blocktrans %} Сборы в мире {% endblocktrans %}:</b> ${{ movie.fess_in_world }}</span>
                        </li>
                        <form action="{% url 'add_rating' %}" method="post" name="rating">
                            {% csrf_token %}
                            <b>{% blocktrans %} Рейтинг {% endblocktrans %}:</b>
                            <input type="hidden" value="{{ movie.id }}" name="movie">
                                {% for k,v in star_form.fields.star.choices %}
                                    <input id="rating{{ k }}" type="radio" name="star" value="{{ k }}">
                                    <label for="rating{{ k }}">{{ v }}</label>
                                {% endfor %}
                            <span class="editContent">4.0</span>
                            <button type="submit">{% blocktrans %} Оценить {% endblocktrans %}</button>
                        </form>
                        <div class="share-desc">
                            <div class="share">
                                <h4 class="editContent"
                                    style="outline: none; cursor: inherit;">
                                    Share:</h4>
                                <ul class="w3layouts_social_list list-unstyled">
                                    <li>
                                        <a href="#" class="w3pvt_facebook editContent"
                                           style="outline: none; cursor: inherit;">
                                                <span class="fa fa-facebook-f"
                                                      style="outline: none; cursor: inherit;"></span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" class="w3pvt_twitter editContent"
                                           style="outline: none; cursor: inherit;">
                                                <span class="fa fa-twitter"
                                                      style="outline: none; cursor: inherit;"></span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" class="w3pvt_dribble editContent"
                                           style="outline: none; cursor: inherit;">
                                                <span class="fa fa-dribbble"
                                                      style="outline: none; cursor: inherit;"></span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </ul>
                </div>
            </div>
            <div class="row sub-para-w3layouts mt-5">

                <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                    {% blocktrans %} {{ movie.title }}{% endblocktrans %}
                </h3>
                <p>

                    {% for image in movie.movieshots_set.all %}
                    <!--                    <div class="row">-->
                    <img src="{{ image.image.url }}" class="img-movieshots" alt="{{ image.description }}">
                    <!--                    </div>-->
                    {% endfor %}
                </p>
                <p class="editContent" style="outline: none; cursor: inherit;">
                    {{ movie.description|safe }}
                </p>
                <p class="mt-3 italic-blue editContent"
                   style="outline: none; cursor: inherit;">
                    <iframe width="560" height="315"
                            src="https://www.youtube.com/embed/A36LahZNUiE?controls=0"
                            frameborder="0" allow="accelerometer; autoplay;
                                                                           encrypted-media; gyroscope; picture-in-picture"
                            allowfullscreen>

                    </iframe>
                </p>
            </div>
            <hr>
            <div class="row">
                <div class="single-form-left">
                    <!-- contact form grid -->
                    <div class="contact-single">
                        <h3 class="editContent" style="outline: none; cursor: inherit;">
                                    <span class="sub-tittle editContent"
                                          style="outline: none; cursor: inherit;">{{ movie.reviews_set.count }}</span>{% blocktrans %} Оставить
                            отзыв {% endblocktrans %}</h3>
                        <form action="{% url 'review-movie' movie.id %}" method="post" class="mt-4" id="formReview">
                            {% csrf_token %}
                            <input type="hidden" name="parent" id="contactparent" value="">
                            <div class="form-group editContent">
                                <label for="contactcomment" class="editContent">
                                    {% blocktrans %}Ваш комментарий {% endblocktrans %} *
                                </label>
                                {{ form.text }}
                            </div>
                            <div class="d-sm-flex">
                                <div class="col-sm-6 form-group p-0 editContent">
                                    <label for="contactusername" class="editContent">
                                        {% blocktrans %}Имя {% endblocktrans %} *
                                    </label>
                                    {{ form.name }}
                                </div>
                                <div class="col-sm-6 form-group ml-sm-3 editContent">
                                    <label for="contactemail" class="editContent">
                                        Email *
                                    </label>
                                    {{ form.email }}
                                </div>
                                {{ form.captcha }}
                            </div>
                            <button type="submit"
                                    class="mt-3 btn btn-success btn-block py-3">
                                {% blocktrans %}Отправить {% endblocktrans %}
                            </button>
                        </form>
                    </div>
                    <!--  //contact form grid ends here -->
                </div>
            </div>
            {% for review in movie.get_review %}
            <div class="media py-5">
                <img src="{% static 'images/te2.jpg' %}" class="mr-3 img-fluid" alt="image">
                <div class="media-body mt-4">
                    <h5 class="mt-0 editContent">{{ review.name }}</h5>
                    <p class="mt-2 editContent">
                        {{ review.text }}
                    </p>
                    <a href="#formReview" onclick="addReview('{{ review.name }}', '{{ review.id }}')">{% blocktrans %} Ответить {% endblocktrans %}</a>
                    {% for rew in review.reviews_set.all %}
                    <div class="media mt-5 editContent">
                        <a class="pr-3" href="#">
                            <img src="{% static 'images/te2.jpg' %}" class="img-fluid "
                                 alt="image">
                        </a>
                        <div class="media-body">
                            <h5 class="mt-0 editContent">{{ rew.name }}</h5>
                            <p class="mt-2 editContent">{{ rew.text }}</p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <script>
    function addReview(name, id){
        document.getElementById("contactparent").value = id;
        document.getElementById("contactcomment").innerText = `${name}, `
    }
    </script>
    {% endblock movie %}

kino_site/templates/movie/movie_list.html
{% extends 'templates/movie/base.html' %}

{% block container %}
<div class="container py-md-3">
{% endblock container %}

{% block movie %}
<div class="left-ads-display col-lg-9">
    <div class="row">
        {% for movie in movie_list %}
        <div class="col-md-4 product-men">
            <div class="product-shoe-info editContent text-center mt-lg-4">
                <div class="men-thumb-item">
                    <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
                </div>
                <div class="item-info-product">
                    <h4 class="">
                        <a href="{{ movie.get_absolute_url }}" class="editContent">{{ movie.title }}</a>
                    </h4>

                    <div class="product_price">
                        <div class="grid-price">
                            <span class="money editContent">{{ movie.tagline }}</span>
                        </div>
                    </div>
                    <ul class="stars">
                        <li><a href="#"><span class="fa fa-star" aria-hidden="true"></span></a></li>
                        <li><a href="#"><span class="fa fa-star" aria-hidden="true"></span></a></li>
                        <li><a href="#"><span class="fa fa-star-half-o" aria-hidden="true"></span></a></li>
                        <li><a href="#"><span class="fa fa-star-half-o" aria-hidden="true"></span></a></li>
                        <li><a href="#"><span class="fa fa-star-o" aria-hidden="true"></span></a></li>
                    </ul>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div>
        {% include 'templates/include/pagination.html' %}
    </div>
</div>
{% endblock movie %}